print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Volumes/Austin's Backup Drive/Angels-Devils/Ang&Dev/Assets/Bed.ma"`)
{		
	file -o "/Volumes/Austin's Backup Drive/Angels-Devils/Ang&Dev/Assets/Bed.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Volumes/Austin's Backup Drive/Angels-Devils/Ang&Dev/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Volumes/Austin's Backup Drive/Angels-Devils/Ang&Dev/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Volumes/Austin's Backup Drive/Angels-Devils/Ang&Dev/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
